
#ifndef LIFERAYNATIVITYUTIL_EXPORT_H
#define LIFERAYNATIVITYUTIL_EXPORT_H

#ifdef LIFERAYNATIVITYUTIL_STATIC_DEFINE
#  define LIFERAYNATIVITYUTIL_EXPORT
#  define LIFERAYNATIVITYUTIL_NO_EXPORT
#else
#  ifndef LIFERAYNATIVITYUTIL_EXPORT
#    ifdef LiferayNativityUtil_EXPORTS
        /* We are building this library */
#      define LIFERAYNATIVITYUTIL_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define LIFERAYNATIVITYUTIL_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef LIFERAYNATIVITYUTIL_NO_EXPORT
#    define LIFERAYNATIVITYUTIL_NO_EXPORT 
#  endif
#endif

#ifndef LIFERAYNATIVITYUTIL_DEPRECATED
#  define LIFERAYNATIVITYUTIL_DEPRECATED __declspec(deprecated)
#endif

#ifndef LIFERAYNATIVITYUTIL_DEPRECATED_EXPORT
#  define LIFERAYNATIVITYUTIL_DEPRECATED_EXPORT LIFERAYNATIVITYUTIL_EXPORT LIFERAYNATIVITYUTIL_DEPRECATED
#endif

#ifndef LIFERAYNATIVITYUTIL_DEPRECATED_NO_EXPORT
#  define LIFERAYNATIVITYUTIL_DEPRECATED_NO_EXPORT LIFERAYNATIVITYUTIL_NO_EXPORT LIFERAYNATIVITYUTIL_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef LIFERAYNATIVITYUTIL_NO_DEPRECATED
#    define LIFERAYNATIVITYUTIL_NO_DEPRECATED
#  endif
#endif

#endif /* LIFERAYNATIVITYUTIL_EXPORT_H */
